name: Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to GitHub Packages
        run: ./gradlew publishToGitHubPackages
        env:
          USERNAME_GITHUB: ${{ secrets.USERNAME_GITHUB }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
